blank_issues_enabled: false
contact_links:
  - name: 🆘 GitHub Community Support
    url: https://github.com/xenitV1/OWL/discussions/categories/q-a
    about: Ask questions and get help from the community
  - name: 📚 Documentation
    url: https://github.com/xenitV1/OWL/wiki
    about: Check our documentation and guides
  - name: 💬 Discussions
    url: https://github.com/xenitV1/OWL/discussions
    about: Join general discussions about OWL
